export interface IProductsUrls {
  PRODUCTS_URL: string
  PRODUCTS_CATEGORIES_URL: string
  PRODUCTS_SEARCH_URL :string
  PRODUCTS_LIKE_URL :string

  PRODUCTS_CATEGORIES_SMARTPHONES_URL: string
  PRODUCTS_CATEGORIES_LAPTOPS_URL: string
  PRODUCTS_CATEGORIES_FRAGRANCES_URL: string
  PRODUCTS_CATEGORIES_SKINCARE_URL: string
  PRODUCTS_CATEGORIES_GROCERIES_URL: string
  PRODUCTS_CATEGORIES_HOMEDECORATION_URL: string
  PRODUCTS_CATEGORIES_FURNITURE_URL: string
  PRODUCTS_CATEGORIES_TOPS_URL: string
  PRODUCTS_CATEGORIES_WOMENSDRESSES_URL: string
  PRODUCTS_CATEGORIES_WOMENSSHOES_URL: string
  PRODUCTS_CATEGORIES_MENSSHIRTS_URL: string
  PRODUCTS_CATEGORIES_MENSSHOES_URL: string
  PRODUCTS_CATEGORIES_MENSWATCHES_URL: string
  PRODUCTS_CATEGORIES_WOMENSWATCHES_URL: string
  PRODUCTS_CATEGORIES_WOMENSBAGS_URL: string
  PRODUCTS_CATEGORIES_WOMENSJEWELLERY_URL: string
  PRODUCTS_CATEGORIES_SUNGLASSES_URL: string
  PRODUCTS_CATEGORIES_AUTOMOTIVE_URL: string
  PRODUCTS_CATEGORIES_MOTORCYCLE_URL: string
  PRODUCTS_CATEGORIES_LIGHTING_URL: string
}

const productsUrls: IProductsUrls = {
  PRODUCTS_URL: '/products',
  PRODUCTS_CATEGORIES_URL: '/products/categories',
  PRODUCTS_SEARCH_URL: '/products/search',
  PRODUCTS_LIKE_URL: '',

  PRODUCTS_CATEGORIES_SMARTPHONES_URL: '/category/smartphones',
  PRODUCTS_CATEGORIES_LAPTOPS_URL: '/category/laptops',
  PRODUCTS_CATEGORIES_FRAGRANCES_URL: '/category/fragrances',
  PRODUCTS_CATEGORIES_SKINCARE_URL: '/category/skincare',
  PRODUCTS_CATEGORIES_GROCERIES_URL: '/category/groceries',
  PRODUCTS_CATEGORIES_HOMEDECORATION_URL: '/category/home-decoration',
  PRODUCTS_CATEGORIES_FURNITURE_URL: '/category/furniture',
  PRODUCTS_CATEGORIES_TOPS_URL: '/category/tops',
  PRODUCTS_CATEGORIES_WOMENSDRESSES_URL: '/category/womens-dresses',
  PRODUCTS_CATEGORIES_WOMENSSHOES_URL: '/category/womens-shoes',
  PRODUCTS_CATEGORIES_MENSSHIRTS_URL: '/category/mens-shirts',
  PRODUCTS_CATEGORIES_MENSSHOES_URL: '/category/mens-shoes',
  PRODUCTS_CATEGORIES_MENSWATCHES_URL: '/category/mens-watches',
  PRODUCTS_CATEGORIES_WOMENSWATCHES_URL: '/category/womens-watches',
  PRODUCTS_CATEGORIES_WOMENSBAGS_URL: '/category/womens-bags',
  PRODUCTS_CATEGORIES_WOMENSJEWELLERY_URL: '/category/womens-jewellery',
  PRODUCTS_CATEGORIES_SUNGLASSES_URL: '/category/sunglasses',
  PRODUCTS_CATEGORIES_AUTOMOTIVE_URL: '/category/automotive',
  PRODUCTS_CATEGORIES_MOTORCYCLE_URL: '/category/motorcycle',
  PRODUCTS_CATEGORIES_LIGHTING_URL: '/category/lighting',
}

export default productsUrls
